version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: dannig-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dannig
      MYSQL_USER: dannig
      MYSQL_PASSWORD: dannig
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dannig-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Adminer para gestión de BD
  adminer:
    image: adminer
    container_name: dannig-adminer
    ports:
      - "8080:8080"
    networks:
      - dannig-network
    restart: unless-stopped

  # Backend API
  backend:
    build: ./backend
    container_name: dannig-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=mysql://dannig:dannig@mysql:3306/dannig
      - JWT_SECRET=secure-token-change-in-production
      # Admin user credentials
      - ADMIN_NAME=Admin
      - ADMIN_EMAIL=admin@dannig.local
      - ADMIN_PASSWORD=admin123
      # Captador user credentials
      - CAPTADOR_NAME=Captador
      - CAPTADOR_EMAIL=captador@dannig.local
      - CAPTADOR_PASSWORD=captador123
      # Oftalmólogo user credentials
      - OFTALMOLOGO_NAME=Dr. Oftalmólogo
      - OFTALMOLOGO_EMAIL=oftalmologo@dannig.local
      - OFTALMOLOGO_PASSWORD=oftalmologo123
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dannig-network
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  # Frontend React
  frontend:
    build: ./frontend
    container_name: dannig-frontend
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - dannig-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  dannig-network:
    driver: bridge
