services:
  mysql:
    image: mysql:8.0
    container_name: dannig-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dannig
      MYSQL_USER: dannig
      MYSQL_PASSWORD: dannig
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    ports:
      - "3307:3306"   
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: dannig-adminer
    ports:
      - "8080:8080"

volumes:
  dbdata:
